### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#108] opened 2016-06-18 14:10 UTC
Hi,
Installation for go 1.6.2 fails with:
```
src/github.com/ory-am/fosite/token/jwt/jwt.go:29: cannot use claims.ToMap() (type map[string]interface {}) as type jwt.Claims in assignment:
	map[string]interface {} does not implement jwt.Claims (missing Valid method)
```

I tried to run this dockerfile:

```
FROM golang:1.6

RUN go get github.com/Masterminds/glide
RUN go get github.com/ory-am/hydra

WORKDIR /go/src/github.com/ory-am/hydra

RUN glide install
RUN go install github.com/ory-am/hydra

ENTRYPOINT /go/bin/hydra host --dangerous-auto-logon

EXPOSE 4444
```

Maybe some dependencies aren't updated?

**Comment by arekkas** [comment] 2016-06-18 16:29
Today a change in go-jwt was merged. Unfortunately it looks like glide does not work recursively on dependencies. Fosite has a glide.lock file but it doesn't look like running glide install in hydra is doing anything. The issue is tracked in https://github.com/ory-am/fosite/issues/51

**Comment by arekkas** [comment] 2016-06-18 16:31
hm that's weird, the glide.lock file has the right jwt-go commit hash linked: https://github.com/ory-am/hydra/blob/master/glide.lock#L15

**Comment by arekkas** [comment] 2016-06-18 16:32
I just ran

```
go get  github.com/ory-am/hydra
cd $GOPATH/github.com/ory-am/hydra
glide install
go run main.go
```

and did not encounter any issues. Are you sure there isn't anything missing or something else going wrong?

**Comment by arekkas** [comment] 2016-06-18 16:36
ok so it looks like go doesn't look for the vendor directory when using aboslute paths. Please do:

```
RUN glide install
RUN go install .
```

instead

**Comment by janekolszak** [comment] 2016-06-18 20:43
I take this dockerfile and build it with --no-cache and get:

```
# docker-compose build --no-cache hydra
Building hydra
Step 1 : FROM golang:1.6
 ---> 78e3813eb6dd
Step 2 : RUN go get github.com/Masterminds/glide
 ---> Running in ae84e92757b1
 ---> 8a9b54e5ae9b
Removing intermediate container ae84e92757b1
Step 3 : RUN go get github.com/ory-am/hydra
 ---> Running in 43992fde66cb
# github.com/ory-am/fosite/token/jwt
src/github.com/ory-am/fosite/token/jwt/jwt.go:29: cannot use claims.ToMap() (type map[string]interface {}) as type jwt.Claims in assignment:
	map[string]interface {} does not implement jwt.Claims (missing Valid method)
ERROR: Service 'hydra' failed to build: The command '/bin/sh -c go get github.com/ory-am/hydra' returned a non-zero code: 2
```

**Comment by arekkas** [comment] 2016-06-18 20:45
Oh I see so the issue is that `go get` also builds the binary. Can you try `go get -d github.com/ory-am/hydra` instead?

**Comment by janekolszak** [comment] 2016-06-18 20:53
yeap, now it works

**Closed** 2016-06-19 10:47 UTC
