### ISSUE TITLE
oidc: at_hash / c_hash mismatch

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#338] opened 2016-12-29 00:02 UTC
Hi!
I get a `c_hash` mismatch when using https://www.npmjs.com/package/openid-client.

Query:
```
code=ayOThtgZ1P-nwPyCFUKlHxHtXKMoVuUozAbS9U6dUE0.uRBdJFQHGtL0Tcek3Ws1F2h0r1h_wkwFn2KJ07k59AM

id_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ3dGEtZCIsImF1dGhfdGltZSI6MTQ4Mjk2ODUyMywiY19oYXNoIjoiWlVVM1RVbGlOWGg2VUZST1pVb3lUWEJQT1VZM1FUMDkiLCJleHAiOjEuNDgyOTcyMTIzZSswOSwiaWF0IjoxLjQ4Mjk2ODUyM2UrMDksImlzcyI6Imh0dHBzOi8vb2lkYy53b3JrdGltZWFzc2lzdGFudC5jb20iLCJub25jZSI6IjhmYWU0NDUxLWRmMTItNGZlYy04Y2M0LTFmNWZmZjQzYjI4MyIsInN1YiI6ImIzMjhjNDcyLTRmMTktNDBmNy1hODM5LWRiMGY3ZTkwYmMyMyJ9.joNG_ZKjJh9z2LTSuFtK1cvK8xgnyx9W_nxx-rSxQYmNR6--382qtSbzK0GWF-qltaN_YZaj3hHVEBv5-brsXGaKhXSyN3J4RLG5qtr1ULGKehUDGJPV-n9NS4zL0GuohnVT8hzRnyQ9rAW2OE9upGL3W_6Jhs8WnTq5qd1_wvDDlRj6r08YrTfaL6Za3V_vD9jUvXvWb3GfS6jdLau2Rm0UL1zV126ODjU4AvhM0vKX2nsSlBHIz2Jwoh46GefxoYlIgsAk5oPNJNVcaxuPev8-4tufdhDJ6GwlQfGgXxo4VVBTjZhaedl1kkxYePNAda8ZofUOFh2LpjHwXmQyPYba9Y1ZWUwNsVknn_k7gwBdwQiEXb7AqzitySGbIP9AJms69ofd6bc8czR9WeaaKPP-GeOLb6WmH5wu88Ilrjo4pOcarv48fj1JoBLnE03a-BI6bDYIW2MXrdR3Rg_5_czLecpUSslKAPNpzTsKT2stSTdUKtcf6BOdfZyGUaqSlCrAQKKsLN55_AQ70Ipb1BmzILPgsFX3wdWUIt0rsiWRN-3x3J5o8ZykuRupZTIFsfyFxt3aGb8KpYfU-SsfePK8WcKN0TEo7d2BFFaQg7EjUOicayNJNqy4pjccMqszJc8ifq6qMHkAlY1zfbT4HDT130gn5As_Su0adu6hpGo

state=feb3fa83-7695-4a4d-9cd6-342a7f5a6baf
```

Decoded id_token:
```json
{
  "alg": "RS256",
  "typ": "JWT"
}
{
  "aud": "wta-d",
  "auth_time": 1482968523,
  "c_hash": "ZUU3TUliNXh6UFROZUoyTXBPOUY3QT09",
  "exp": 1482972123,
  "iat": 1482968523,
  "iss": "https://oidc.worktimeassistant.com",
  "nonce": "8fae4451-df12-4fec-8cc4-1f5fff43b283",
  "sub": "b328c472-4f19-40f7-a839-db0f7e90bc23"
}
```

`c_hash` in the `id_token` seems to be too wrong. `sha256sum` returns:

```bash
echo -n ayOThtgZ1P-nwPyCFUKlHxHtXKMoVuUozAbS9U6dUE0.uRBdJFQHGtL0Tcek3Ws1F2h0r1h_wkwFn2KJ07k59AM | sha256sum

784ecc21be71ccf4cd789d8ca4ef45ec9a7d051b98747b26be93482e8e4eecf7
```

**Comment by arekkas** [comment] 2016-12-29 09:22
Thanks for reporting, I think I know what the issue is. Go is encoding `[]byte` values as base64 when using `json.Encode()` which leads to encoding the c_hash value twice [here](https://github.com/ory-am/fosite/blob/95caa96835a1254ba3f8f4a21e635fe6da34f0fe/handler/openid/flow_hybrid.go#L74) and isn't catched by the unit tests, as Go also base64 decodes the values when it finds a `[]byte` slice in the struct.

**Comment by janekolszak** [comment] 2016-12-29 11:07
Maybe `at_hash` is also broken?

**Comment by arekkas** [comment] 2016-12-29 11:15
Yes, I think the bug applies to all hashes!

**Comment by arekkas** [comment] 2016-12-29 22:53
I hope the commit above resolves this issue. Would you mind trying it out? The PR is #329

**Comment by janekolszak** [comment] 2016-12-30 09:12
Are the prereleases build anywhere?

**Comment by arekkas** [comment] 2016-12-30 09:22
No unfortunately not, I'll just release it and fix it in the next minor release if there's still something wrong

**Comment by arekkas** [comment] 2016-12-30 09:25
I'll reopen if the issues persist

**Comment by arekkas** [comment] 2017-01-02 11:24
Ah, apparently the problem now is the padding, Go adds two equals `E0GjRojb2VZyS0GbugtR3Q==` but oidc-token-hash (used by open-id-client) requires no padding `E0GjRojb2VZyS0GbugtR3Q`. The problem itself is within the `oidc-token-hash` library, which uses predefined lengths to validate the input, but does not strip away padding:

```
const LENGTHS = { 22: 'sha256', 32: 'sha384', 43: 'sha512' };
const ALGS = ['sha256', 'sha384', 'sha512'];

function validate(actual, token) {
  if (!actual) return false;
  const alg = LENGTHS[actual.length];
  if (!alg) return false;
  return generate(token, alg) === actual;
}
```

Since libraries should be able to deal with base64url encoding and padding (which is *not* omitted by default), I will create a patch for the dependency. I was not able to find information on padding in the oidc spec.

The patch is quite trivial:

```js
function validate(actual, token) {
  if (!actual) return false;
  actual = actual.replace(/=+$/, '')
  const alg = LENGTHS[actual.length];
  if (!alg) return false;
  return generate(token, alg) === actual;
}
```

**Comment by arekkas** [comment] 2017-01-02 11:28
The PR is now here: https://github.com/panva/oidc-token-hash/pull/1

Please notify the maintainers of the change, maybe they need to upgrade their package.json

**Comment by janekolszak** [comment] 2017-01-02 11:52
Thank you!
But are you sure this is the right way? I'm certain the library already works with google OIDC.
Maybe hydra should strip the padding?

**Comment by arekkas** [comment] 2017-01-02 11:54
No, I'm not certain that the padding should be left in, but let's see what the maintainer says! The library (oidc-token-hash) does not seem to be certified and also not widely used (this was the first PR). Unfortunately, I could not find a oidc connect reference implementation for Go.

**Comment by janekolszak** [comment] 2017-01-02 11:57
The linki https://www.npmjs.com/package/openid-client says it's certified.

**Comment by arekkas** [comment] 2017-01-02 11:58
Yes, that one is certified, I'm just not sure if that includes the oidc-token-hash dependency :)

**Comment by arekkas** [comment] 2017-01-02 12:01
Even the reference table on wikipedia is confusing :D

https://en.wikipedia.org/wiki/Base64#Implementations_and_history

**Comment by janekolszak** [comment] 2017-01-02 12:02
And I can't find any base64url encoded values (in the docs and here:
https://community.pingidentity.com/servlet/fileField?retURL=%2Fapex%2FPingIdentityArticle%3Fid%3DkA340000000Gs7WCAS&entityId=ka340000000GvdRAAS&field=Associated_File__Body__s ) that contain `==`

**Comment by arekkas** [comment] 2017-01-02 12:04
Let's wait and see what the maintainer says. I'm open to remove the padding, just want to make sure it's not a special case :)

**Comment by panva** [comment] 2017-01-02 12:05
`=` is not url safe, so not part of base64url :) but i'm happy to accept the PR as it does not necessarily break anything per-se

**Comment by arekkas** [comment] 2017-01-02 12:06
Ok, I think I'll just omit it then! Feel free to accept/close the PR :)

**Comment by arekkas** [comment] 2017-01-02 12:10
Resolved with https://github.com/ory-am/fosite/releases/tag/v0.6.11

**Comment by panva** [comment] 2017-01-02 12:11
I think stripping the paddings to produce valid hashes is the way to go, nevertheless the PR is merged, version published and @janekolszak just needs to update his locked dependencies.

**Comment by arekkas** [comment] 2017-01-02 12:11
Ok, thanks for the quick response times!

**Comment by panva** [comment] 2017-01-02 12:18
oidc-token-hash is simply a shared piece of code for [https://github.com/panva/node-openid-client](panva/node-openid-client) and [https://github.com/panva/node-oidc-provider](panva/node-oidc-provider) to produce and validate these hashes, made no sense to have the same js file in both libraries :)

**Comment by arekkas** [comment] 2017-01-02 12:39
@panva sorry if I ask so directly, but how did you get the library certified and did it cost money? I intend to get some certifications for this repo as well!

**Closed** 2017-01-02 13:09 UTC
Labels: upstream

**Comment by panva** [comment] 2017-01-02 15:59
@arekkas the tools and processes are linked at http://openid.net/certification/, they are btw great tools to validate your functionality, for example the padding would have been checked and rejected by the OP testing tool. Hit me up via email if you'd like more details.

**Comment by arekkas** [comment] 2017-01-02 16:03
Awesome, thank you so much!
