### ISSUE TITLE
Need a better health check for a load balancer

### ISSUE THREAD

**Issue by abdollar** [ory-am/hydra#251] opened 2016-09-15 23:19 UTC
I am currently using the /oauth2/auth path for a load balancer health check; where I check for a 302 response code. This unfortunately throws errors into the log.

Is there a better health check to use for a load balancer?

Happy to submit a PR but I personally was not sure what this should even look like. I liked the /oauth/auth endpoint but the error messages generated in the logs are too verbose.

**Comment by arekkas** [comment] 2016-09-16 06:01
You can customize the verbosity of logs with `LOG_LEVEL=<level>`, see https://github.com/ory-am/hydra/blob/master/main.go#L18

What sort of health check do you need? Just a simple ping/pong?

Otherwise, health monitoring is tracked in #216

**Comment by arekkas** [comment] 2016-09-21 09:22
ping @abdollar

**Comment by abdollar** [comment] 2016-09-21 18:30
@arekkas In terms of the health check. It would be great to use something that is an indicator of the health of the system but its not a high priority at this stage. One thought I had was to create a specific client for the load balancer so it actually generated a token and use the client_id and secret as part of the health check. This could then be tied to an auto scaling infrastructure.

**Comment by arekkas** [comment] 2016-09-22 07:15
Ok, then I'm going to close this as a dupe of #216 - thanks for the response :)

**Closed by arekkas** 2016-09-22 07:15 UTC
Labels: enhancement
